name: flutter_camera_location_map
description: A new Flutter project.

version: 0.5.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  image_picker: ^0.8.4+4
  path_provider: ^2.0.8
  path: ^1.8.0
  sqflite: ^2.0.2
  location: ^4.3.0
  google_maps_flutter: ^2.1.1
  http: ^0.13.4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

